# Generated by Django 2.1.5 on 2019-03-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50, null=True, unique=True)),
                ('description', models.CharField(max_length=100, null=True, unique=True)),
                ('trend', models.CharField(choices=[('ASC', 'ASCENDING'), ('DESC', 'DESCENDING'), ('FLAT', 'FLAT')], default='FLAT', max_length=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='carstatistic',
            unique_together={('title', 'created')},
        ),
    ]
