# Generated by Django 2.1.5 on 2019-03-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carstatistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstatistic',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
