# Generated by Django 2.1.5 on 2019-03-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carstatistic', '0002_auto_20190312_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='carstatistic',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carstatistic',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carstatistic',
            name='number',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
