# Generated by Django 2.1.5 on 2019-03-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carstatistic', '0003_auto_20190312_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstatistic',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
