# Generated by Django 2.1.5 on 2019-03-13 09:42

import carstatistic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carstatistic', '0004_auto_20190312_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstatistic',
            name='title',
            field=models.CharField(choices=[(carstatistic.models.CarStatisticTitle('Number of referenced cars'), 'Number of referenced cars'), (carstatistic.models.CarStatisticTitle('Number of retailers scraped'), 'Number of retailers scraped'), (carstatistic.models.CarStatisticTitle('Average Car Price'), 'Average Car Price')], max_length=50),
        ),
    ]
