# Generated by Django 2.1.5 on 2019-03-13 10:48

import carstatistic.models
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carstatistic', '0004_auto_20190312_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstatistic',
            name='title',
            field=enumchoicefield.fields.EnumChoiceField(default=carstatistic.models.CarStatisticTitle(4), enum_class=carstatistic.models.CarStatisticTitle, max_length=11),
        ),
        migrations.AlterField(
            model_name='carstatistic',
            name='trend',
            field=enumchoicefield.fields.EnumChoiceField(default=carstatistic.models.Trend(3), enum_class=carstatistic.models.Trend, max_length=4),
        ),
    ]
