# Generated by Django 2.1.5 on 2019-02-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('km_number', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('car_type', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('reg_date', models.DateField(blank=True)),
                ('gear_box', models.CharField(blank=True, max_length=10)),
                ('motor_type', models.CharField(blank=True, max_length=10)),
                ('petrol_type', models.CharField(blank=True, max_length=10)),
                ('color', models.CharField(blank=True, max_length=10)),
                ('doors_number', models.IntegerField(blank=True)),
                ('vendor_link', models.CharField(blank=True, max_length=100)),
                ('vendor_ref', models.CharField(blank=True, max_length=50)),
                ('owner_number', models.IntegerField(blank=True)),
                ('reg_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
