# Generated by Django 2.1.5 on 2019-03-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_auto_20190301_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gear_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
