# Generated by Django 2.1.5 on 2019-03-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_car_gear_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
