# Generated by Django 2.1.5 on 2019-03-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_auto_20190304_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vendor_ref',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
