# Generated by Django 2.1.5 on 2019-03-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_auto_20190304_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='vendor_ref',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
