# Generated by Django 2.1.5 on 2019-03-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0009_auto_20190304_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCar',
        ),
    ]
