# Generated by Django 2.1.5 on 2019-03-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0010_delete_testcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='km_number',
            field=models.IntegerField(default=0),
        ),
    ]
