# Generated by Django 2.1.5 on 2019-03-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0014_auto_20190307_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='vendor_ref',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
