# Generated by Django 2.1.5 on 2019-03-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0015_auto_20190307_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vendor_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
